title: JhammerZ Sovereign Hub
description: Autonomous Distributed Network
url: https://jhammerz.github.io
baseurl: ""
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
include:
  - .nojekyll
  - .hfid
  - .well-known
  - llms.txt
  - llms-full.txt
  - _headers
  - entities.json
  - chain.json
  - public
  - docs
  - dist
exclude:
  - node_modules/
  - vendor/
  - src/
