name = "lysander-w4"
main = "index.js"
account_id = "8e06551..."
compatibility_date = "2026-08-18"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "W4_ROOM"
class_name = "W4Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["W4Room"]

[[d1_databases]]
binding = "DB"
database_name = "w4-db"
database_id = "67f06052-2425-4200-bb94-835dd6792f8b"

[analytics_engine_datasets]
binding = "AE"
dataset = "lysander_metrics"
