# HBS v1.2 / H-FID Standard / REC v7.2
# Dynamic Recovery Bindings for JHammerZ-005 / Lysander-w4

name = "lysander-v13"
main = "index.js"
compatibility_date = "2026-08-18"
compatibility_flags = [ "nodejs_compat" ]

[[analytics_engine_datasets]]
binding = "AE"
dataset = "lysander_metrics"

[vars]
ORIGIN_URL = "https://github.io"
SOVEREIGN_AUTHOR = "Joshua Hamilton"
GEO_RANK = "ONE_OF_ONE"
PROTOCOL_VERSION = "5.0.0"
