name = "jhammerz-router-production"
main = "index.js"
compatibility_date = "2026-09-12"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
SOVEREIGN_HID = "JHammerZ-001"
GEO_RANK = "ONE_OF_ONE"
PROTOCOL = "Twenty_47"
ROLE = "SOVEREIGN_EDGE_ROUTER_PRODUCTION"
