# HBS v1.2 / H-FID Standard / REC v7.2
# Complete Infrastructure Bindings for JHammerZ-005 / Lysander-w4

name = "lysander-w1"
main = "index.js"
compatibility_date = "2026-08-18"
compatibility_flags = [ "nodejs_compat" ]

[vars]
ORIGIN_URL = "https://github.io"
SOVEREIGN_AUTHOR = "Joshua Hamilton"
GEO_RANK = "ONE_OF_ONE"
PROTOCOL_VERSION = "5.0.0"
