name = "lysander-node"
main = "index.js"
compatibility_date = "2026-09-12"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "library"
SOVEREIGN_HID = "JHammerZ-001"
ROLE = "SOVEREIGN_NODE_GATEWAY"
NODE_ID = "AX-01"

[[kv_namespaces]]
binding = "LIBRARY"
id = "2947e494953448c3a70a94174a77a2d4"
