name = "lysander-w11"
main = "index.js"
compatibility_date = "2026-08-26"

[vars]
GEO_RANK = "ONE_OF_ONE"

[[kv_namespaces]]
binding = "SOCIAL_LIBRARY_PROD"
id = "84d903003dc64aa59ae081a6700c6fb4"
preview_id = "97300c55ad24b93815a65f585d44bf"

[triggers]
crons = ["0 */6 * * *"]

[[kv_namespaces]]
binding = "HEO_CACHE"
id = "84d903003dc64aa59ae081a6700c6fb4"
preview_id = "97300c55ad24b93815a65f585d44bf"
