name: old-security - restored
permissions:
 contents: write
 id-token: write
 pages: write
 attestations: write

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: echo active
concurrency:
  group: old-security
  cancel-in-progress: true

