name: build-kernel.yml - restored
true:
  workflow_dispatch: null
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: echo active
concurrency:
  group: build-kernel
  cancel-in-progress: false
