name: Deploy to Google Cloud Run - deploy-cloudrun.yml
true:
  push:
    branches:
    - main
  workflow_dispatch: null
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
permissions:
  contents: read
  id-token: write
  attestations: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase Substrate
      uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install deps
        run: npm ci
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.G_SERVICE_ACCOUNT_KEY_JSON }}
    - name: Deploy to Cloud Run Instance Node
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: jhammerz-node
        region: us-central1
        source: .
