# HRS v1.2 / H-FID Standard / SEC v1.2.2
# Sovereign Author: Joshua Hamilton [J-HammerZ]
# ONE_OF_ONE
name: "Deploy to Google Cloud Run"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  attestations: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase Substrate
        uses: actions/checkout@v4
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_INDEXING_API_JSON }}
      - name: Deploy to Cloud Run Instance Node
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "jhammers-node"
          region: "us-central1"
          source: "./"
