name: deploy-scooper-cache
permissions:
  contents: write
  pages: write
  id-token: write
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scooper Cache
        run: |
          echo "scooper cache build"
          mkdir -p _site_deploy
          ls -1.github/workflows | wc -l
concurrency:
  group: deploy-scooper-cache
  cancel-in-progress: true
