# HBS v1.2 / H-FID Standard / REC v7.2
# Copyright (c) 2026 Joshua Hamilton [J-HammerZ]
# Licensed under MIT License
# Sovereign Author: Joshua Hamilton

name: "Deploy to Google Cloud Run"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Substrate Node
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_INDEXING_API_JSON }}

      - name: Deploy to Cloud Run Instance Node
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "jhammerz-node"
          region: "us-central1"
          source: "."
