name: FORCE_INDEX_NODES
on:
  push:
    branches: 

jobs:
  FORCE_INDEX_NODES:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build check
        run: echo "Build passed"
