name: H-FID Threat Hunt
permissions:
  contents: write
  id-token: write
  pages: write
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Threat Hunt
        run: |
          echo "Scanning..."
          grep -r "REGEX".github/workflows/ | grep -v "trap cleared" | grep -v "grep -r" || echo "CLEAN - no traps"
          ls -1.github/workflows/*.yml | wc -l
