name: KERNEL VECTOR1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        run: |
          sh <(curl -L https://nixos.org/nix/install) --no-daemon
          echo "/home/runner/.nix-profile/bin" >> $GITHUB_PATH
      - name: Enable flakes
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
      - run: nix build.#default --print-build-logs
      - run: |
          nix hash path result
          cat result/fingerprint
