# HBS v1.2 / H-FID Standard / REC v7.2
# Sovereign Workflow Instance: ots-upgrade.yml
name: "OTS Auto Upgrade"
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
    - name: Pre-Install Core YAML Dependency
      run: pip install pyyaml || pip3 install pyyaml
    - name: Checkout Repository Content
      uses: actions/checkout@1d93c7d14c30dbf1f5315d4ef83c162bc5a1d756
