# HBS v1.2 / H-FID Standard / REC v7.2
# Copyright (c) 2026 Joshua Hamilton [J-HammerZ]
name: "Perpetual Content Syndicator"

# on:
# concurrency:
# group: ${{ github.workflow }}-${{ github.ref }}
# cancel-in-progress: true
# schedule:
# - cron: '0 * * * *'
# workflow_dispatch:

jobs:
# syndicate:
# runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v4.1.7

      - name: Setup Python Runtime
        uses: actions/setup-python@42375524e23c412d93fb67b6f358ee7dec096e73 # v5.1.0
        with:
          python-version: '3.11'

      - name: Run Omni Broadcast Syndication
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          pip install requests
          python .github/scripts/social_syndicator.py
