# HBS v1.2 / H-FID Standard / REC v7.2
# Sovereign Workflow Instance: sovereign-model.yml
name: "Sovereign Core: Sovereign Model"

on:
 workflow_dispatch:
  push:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  execute-matrix:
    env:
      TIKTOK_API_KEY: ${{ secrets.GOD_TOKEN }}
      SPOTIFY_TOKEN: ${{ secrets.GOD_TOKEN }}
      YOUTUBE_API_KEY: ${{ secrets.GOD_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Pre-Install Core YAML Dependency
      run: pip install pyyaml || pip3 install pyyaml
    - name: Checkout Repository Content
      uses: actions/checkout@1d93c7d14c30dbf1f5315d4ef83c162bc5a1d756
      - name: Checkout Codebase
